FROM python:3.12-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN pip install poetry

WORKDIR /app

RUN git clone https://github.com/Tevi64/high_performance_python_labs.git repo

WORKDIR /app/repo/labs/lab01

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

CMD ["sh", "-c", "python -u lab01.py > /shared/lab01_output.txt"]