FROM python:3.12-slim

RUN apt-get update && apt-get install -y git build-essential && rm -rf /var/lib/apt/lists/*
RUN pip install poetry

WORKDIR /app

RUN git clone https://github.com/Tevi64/high_performance_python_labs.git repo

WORKDIR /app/repo/labs/lab02

RUN poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi --no-root

RUN poetry run python build.py build_ext --inplace

CMD ["sh", "-c", "python -u lab02.py > /shared/lab02_output.txt"]